# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: jhin

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/jhin
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

archives:
  - id: jhin
    formats: [tar.gz]

changelog:
  disable: true

release:
  mode: keep-existing
  use_existing_draft: true
