name: Release

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Token
        uses: actions/create-github-app-token@v2
        id: gh-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Release
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.gh-token.outputs.token }}

      - name: Checkout
        if: ${{ steps.release.outputs['release_created'] }}
        uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Setup Go
        if: ${{ steps.release.outputs['release_created'] }}
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build and Release Artifact
        if: ${{ steps.release.outputs['release_created'] }}
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ steps.gh-token.outputs.token }}
